try {
  //  код, который может выбросить ошибку
} catch (error) {
  //  код для обработки ошибки
  throw new Error('Ошибка в блоке catch');
}